trace: true

---

logging:
  level:
    org.springframework.security.web.FilterChainProxy: DEBUG
---

server:
  port: 8083
  servlet:
    context-path: /myapp/api

---

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: no_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      
---

logging:
  file:
    name: /hlffapp/myapp/myapp.log